//! Uniform null-argument rejection across the C ABI (DESIGN.md §6.1).
//!
//! Every status-returning entry point that takes at least one pointer must reject an all-null
//! call with [`PrismPdfStatus::NullArgument`] — never crash, never unwind, never succeed. The
//! shared `utf8`/`free_handle`/`guard` helpers make that the single code path; this generated
//! sweep pins it for each exported function. One line per entry point, kept unwrapped on purpose.
//!
//! The single scalar-first exception: `prismpdf_composition_container_set_heading` range-checks
//! its documented `level` argument (1..=6) before the pointers, so the sweep passes a valid one.

use crate::*;
use std::ptr::{null, null_mut};

#[test]
#[rustfmt::skip]
fn every_pointer_taking_status_fn_rejects_all_null_arguments() {
    let mut failures: Vec<String> = Vec::new();
    macro_rules! check {
        ($name:ident($($arg:expr),*)) => {
            let status = unsafe { $name($($arg),*) };
            if status != PrismPdfStatus::NullArgument {
                failures.push(format!("{}: {:?}", stringify!($name), status));
            }
        };
    }
    check!(prismpdf_page_spec_set_media_box(null_mut(), 0.0, 0.0, 0.0, 0.0));
    check!(prismpdf_page_spec_add_standard_font(null_mut(), null(), PrismPdfStdFont::Helvetica));
    check!(prismpdf_page_spec_add_embedded_font(null_mut(), null()));
    check!(prismpdf_page_spec_add_image(null_mut(), null(), null()));
    check!(prismpdf_content_bytes(null(), null_mut(), null_mut()));
    check!(prismpdf_content_save(null_mut()));
    check!(prismpdf_content_restore(null_mut()));
    check!(prismpdf_content_transform(null_mut(), 0.0, 0.0, 0.0, 0.0, 0.0, 0.0));
    check!(prismpdf_content_set_line_width(null_mut(), 0.0));
    check!(prismpdf_content_set_fill_gray(null_mut(), 0.0));
    check!(prismpdf_content_set_stroke_gray(null_mut(), 0.0));
    check!(prismpdf_content_set_fill_rgb(null_mut(), 0.0, 0.0, 0.0));
    check!(prismpdf_content_set_stroke_rgb(null_mut(), 0.0, 0.0, 0.0));
    check!(prismpdf_content_set_fill_cmyk(null_mut(), 0.0, 0.0, 0.0, 0.0));
    check!(prismpdf_content_move_to(null_mut(), 0.0, 0.0));
    check!(prismpdf_content_line_to(null_mut(), 0.0, 0.0));
    check!(prismpdf_content_curve_to(null_mut(), 0.0, 0.0, 0.0, 0.0, 0.0, 0.0));
    check!(prismpdf_content_rect(null_mut(), 0.0, 0.0, 0.0, 0.0));
    check!(prismpdf_content_close_path(null_mut()));
    check!(prismpdf_content_stroke(null_mut()));
    check!(prismpdf_content_fill(null_mut()));
    check!(prismpdf_content_fill_and_stroke(null_mut()));
    check!(prismpdf_content_begin_text(null_mut()));
    check!(prismpdf_content_end_text(null_mut()));
    check!(prismpdf_content_set_char_spacing(null_mut(), 0.0));
    check!(prismpdf_content_set_word_spacing(null_mut(), 0.0));
    check!(prismpdf_content_set_leading(null_mut(), 0.0));
    check!(prismpdf_content_text_move(null_mut(), 0.0, 0.0));
    check!(prismpdf_content_set_text_matrix(null_mut(), 0.0, 0.0, 0.0, 0.0, 0.0, 0.0));
    check!(prismpdf_content_next_line(null_mut()));
    check!(prismpdf_content_begin_artifact(null_mut()));
    check!(prismpdf_content_end_marked_content(null_mut()));
    check!(prismpdf_content_set_fill_color_space(null_mut(), null()));
    check!(prismpdf_content_set_fill_color(null_mut(), null(), 0));
    check!(prismpdf_content_do_xobject(null_mut(), null()));
    check!(prismpdf_content_inline_image(null_mut(), 0, 0, null(), 0, null(), 0));
    check!(prismpdf_content_set_font(null_mut(), null(), 0.0));
    check!(prismpdf_content_show_text(null_mut(), null(), 0));
    check!(prismpdf_content_show_str(null_mut(), null()));
    check!(prismpdf_content_show_glyphs(null_mut(), null(), 0));
    check!(prismpdf_content_begin_marked_content(null_mut(), null(), 0));
    check!(prismpdf_content_begin_af_marked_content(null_mut(), null()));
    check!(prismpdf_struct_node_set_alt(null_mut(), null()));
    check!(prismpdf_struct_node_set_actual_text(null_mut(), null()));
    check!(prismpdf_struct_node_set_lang(null_mut(), null()));
    check!(prismpdf_struct_node_set_namespace(null_mut(), null()));
    check!(prismpdf_struct_node_set_id(null_mut(), null()));
    check!(prismpdf_struct_node_add_reference(null_mut(), null()));
    check!(prismpdf_struct_node_add_name_attribute(null_mut(), null(), null(), null()));
    check!(prismpdf_struct_node_add_integer_attribute(null_mut(), null(), null(), 0));
    check!(prismpdf_struct_node_add_text_attribute(null_mut(), null(), null(), null()));
    check!(prismpdf_struct_node_add_content(null_mut(), 0, 0));
    check!(prismpdf_struct_node_add_widget(null_mut(), 0));
    check!(prismpdf_struct_node_add_annotation(null_mut(), 0));
    check!(prismpdf_struct_node_add_child(null_mut(), null_mut()));
    check!(prismpdf_struct_node_associate_file(null_mut(), null(), null(), null(), null(), null(), 0));
    check!(prismpdf_builder_add_structure_node(null_mut(), null_mut()));
    check!(prismpdf_builder_set_structure_namespace(null_mut(), null()));
    check!(prismpdf_builder_build(null(), null_mut(), null_mut()));
    check!(prismpdf_builder_build_for(null(), 0, 0, null_mut(), null_mut()));
    check!(prismpdf_builder_set_media_box(null_mut(), null()));
    check!(prismpdf_builder_set_version(null_mut(), 0, 0));
    check!(prismpdf_builder_set_info(null_mut(), null(), null()));
    check!(prismpdf_builder_clear_info(null_mut()));
    check!(prismpdf_builder_set_metadata_xmp(null_mut(), null(), 0));
    check!(prismpdf_builder_set_lang(null_mut(), null()));
    check!(prismpdf_builder_set_file_id(null_mut(), null(), 0));
    check!(prismpdf_builder_set_utf8_text_strings(null_mut()));
    check!(prismpdf_builder_set_display_doc_title(null_mut(), false));
    check!(prismpdf_builder_add_page(null_mut(), null(), 0, null(), null(), 0));
    check!(prismpdf_builder_add_page_spec(null_mut(), null_mut()));
    check!(prismpdf_builder_add_outline(null_mut(), null(), 0));
    check!(prismpdf_builder_attach_file(null_mut(), null(), null(), null(), null(), null(), 0));
    check!(prismpdf_builder_add_link_uri(null_mut(), 0, null(), null(), null()));
    check!(prismpdf_builder_add_link_page(null_mut(), 0, null(), 0, null()));
    check!(prismpdf_builder_add_link_element(null_mut(), 0, null(), null(), null()));
    check!(prismpdf_builder_add_link_document_part(null_mut(), 0, null(), 0, null()));
    check!(prismpdf_builder_add_note(null_mut(), 0, null(), null()));
    check!(prismpdf_builder_add_checkbox(null_mut(), 0, null(), null(), false, null()));
    check!(prismpdf_builder_set_title(null_mut(), null()));
    check!(prismpdf_builder_set_author(null_mut(), null()));
    check!(prismpdf_builder_set_subject(null_mut(), null()));
    check!(prismpdf_builder_set_keywords(null_mut(), null()));
    check!(prismpdf_builder_set_creator(null_mut(), null()));
    check!(prismpdf_page_annotations(null(), 0, null_mut()));
    check!(prismpdf_annotation_list_len(null(), null_mut()));
    check!(prismpdf_annotation_list_get(null(), 0, null_mut()));
    check!(prismpdf_annotation_subtype(null(), null_mut()));
    check!(prismpdf_annotation_rect(null(), null_mut()));
    check!(prismpdf_annotation_contents(null(), null_mut()));
    check!(prismpdf_annotation_uri(null(), null_mut()));
    check!(prismpdf_annotation_dest_page(null(), null_mut()));
    check!(prismpdf_document_form_fields(null(), null_mut()));
    check!(prismpdf_form_field_list_len(null(), null_mut()));
    check!(prismpdf_form_field_list_get(null(), 0, null_mut()));
    check!(prismpdf_form_field_name(null(), null_mut()));
    check!(prismpdf_form_field_type(null(), null_mut()));
    check!(prismpdf_form_field_value(null(), null_mut()));
    check!(prismpdf_document_fill_form(null(), null(), null(), 0, null_mut(), null_mut()));
    check!(prismpdf_document_fill_form_report(null(), null(), null(), 0, null_mut()));
    check!(prismpdf_document_flatten_form(null(), null_mut(), null_mut()));
    check!(prismpdf_document_flatten_form_report(null(), null_mut()));
    check!(prismpdf_document_outline(null(), null_mut()));
    check!(prismpdf_outline_list_len(null(), null_mut()));
    check!(prismpdf_outline_list_get(null(), 0, null_mut()));
    check!(prismpdf_outline_item_title(null(), null_mut()));
    check!(prismpdf_outline_item_dest_page(null(), null_mut()));
    check!(prismpdf_outline_item_child_count(null(), null_mut()));
    check!(prismpdf_outline_item_child(null(), 0, null_mut()));
    check!(prismpdf_document_attachments(null(), null_mut()));
    check!(prismpdf_attachment_list_len(null(), null_mut()));
    check!(prismpdf_attachment_list_get(null(), 0, null_mut()));
    check!(prismpdf_attachment_name(null(), null_mut()));
    check!(prismpdf_attachment_data(null(), null_mut(), null_mut()));
    check!(prismpdf_attachment_mime(null(), null_mut()));
    check!(prismpdf_attachment_relationship(null(), null_mut()));
    check!(prismpdf_attachment_description(null(), null_mut()));
    check!(prismpdf_document_fonts(null(), null_mut()));
    check!(prismpdf_font_list_len(null(), null_mut()));
    check!(prismpdf_font_list_get(null(), 0, null_mut()));
    check!(prismpdf_font_base_font(null(), null_mut()));
    check!(prismpdf_font_subtype(null(), null_mut()));
    check!(prismpdf_font_program_format(null(), null_mut()));
    check!(prismpdf_font_program(null(), null_mut(), null_mut()));
    check!(prismpdf_font_metrics(null(), null_mut(), null_mut()));
    check!(prismpdf_font_family_name(null(), null_mut()));
    check!(prismpdf_document_subset_fonts(null(), null_mut(), null_mut()));
    check!(prismpdf_document_subset_fonts_report(null(), null_mut()));
    check!(prismpdf_page_images(null(), 0, null_mut()));
    check!(prismpdf_image_list_len(null(), null_mut()));
    check!(prismpdf_image_list_get(null(), 0, null_mut()));
    check!(prismpdf_image_info(null(), null_mut(), null_mut(), null_mut()));
    check!(prismpdf_image_color_space(null(), null_mut()));
    check!(prismpdf_image_components(null(), null_mut()));
    check!(prismpdf_image_kind(null(), null_mut()));
    check!(prismpdf_image_data(null(), null_mut(), null_mut()));
    check!(prismpdf_document_xmp(null(), null_mut()));
    check!(prismpdf_document_info(null(), null(), null_mut()));
    check!(prismpdf_document_creation_date(null(), null_mut()));
    check!(prismpdf_document_modification_date(null(), null_mut()));
    check!(prismpdf_page_text_positioned(null(), 0, null_mut()));
    check!(prismpdf_composition_add_page(null_mut(), null(), null_mut()));
    check!(prismpdf_composition_page_set_header(null_mut(), 0, null_mut()));
    check!(prismpdf_composition_page_set_footer(null_mut(), 0, null_mut()));
    check!(prismpdf_composition_set_tagged_language(null_mut(), null()));
    check!(prismpdf_composition_container_set_column(null_mut(), 0.0, null_mut()));
    check!(prismpdf_composition_column_add_item(null_mut(), null_mut()));
    check!(prismpdf_composition_container_set_row(null_mut(), null_mut()));
    check!(prismpdf_composition_row_add_fixed(null_mut(), 0.0, null_mut()));
    check!(prismpdf_composition_row_add_relative(null_mut(), 0.0, null_mut()));
    check!(prismpdf_composition_row_add_auto(null_mut(), null_mut()));
    check!(prismpdf_composition_container_set_table(null_mut(), null_mut()));
    check!(prismpdf_composition_table_add_fixed_column(null_mut(), 0.0));
    check!(prismpdf_composition_table_add_relative_column(null_mut(), 0.0));
    check!(prismpdf_composition_table_add_auto_column(null_mut()));
    check!(prismpdf_composition_table_set_header(null_mut(), null_mut()));
    check!(prismpdf_composition_table_add_row(null_mut(), null_mut()));
    check!(prismpdf_composition_table_row_add_cell(null_mut(), null_mut()));
    check!(prismpdf_composition_container_set_semantic(null_mut(), PrismPdfCompositionSemantic::Paragraph, null_mut()));
    check!(prismpdf_composition_container_set_heading(null_mut(), 1, null_mut()));
    check!(prismpdf_composition_container_set_link(null_mut(), null(), null(), null_mut()));
    check!(prismpdf_composition_container_set_figure(null_mut(), null(), null_mut()));
    check!(prismpdf_composition_container_set_image(null_mut(), null(), PrismPdfCompositionImageSizing::Fit, 0.0, 0.0));
    check!(prismpdf_composition_container_set_padding(null_mut(), 0.0, null_mut()));
    check!(prismpdf_composition_container_set_width(null_mut(), 0.0, null_mut()));
    check!(prismpdf_composition_container_set_height(null_mut(), 0.0, null_mut()));
    check!(prismpdf_composition_container_set_alignment(null_mut(), PrismPdfCompositionHorizontalAlign::Left, PrismPdfCompositionVerticalAlign::Top, null_mut()));
    check!(prismpdf_composition_container_set_extend(null_mut(), null_mut()));
    check!(prismpdf_composition_container_set_text(null_mut(), null(), null()));
    check!(prismpdf_composition_container_set_page_break(null_mut()));
    check!(prismpdf_composition_build(null_mut(), null_mut(), null_mut()));
    check!(prismpdf_last_error(null_mut()));
    check!(prismpdf_error_info_status(null(), null_mut()));
    check!(prismpdf_error_info_message(null(), null_mut()));
    check!(prismpdf_document_open(null(), 0, null_mut()));
    check!(prismpdf_document_open_with_password(null(), 0, null(), 0, null_mut()));
    check!(prismpdf_document_catalog_object(null(), null_mut()));
    check!(prismpdf_document_page_object(null(), 0, null_mut()));
    check!(prismpdf_document_get_object(null(), 0, 0, null_mut()));
    check!(prismpdf_document_resolve_object(null(), null(), null_mut()));
    check!(prismpdf_object_kind(null(), null_mut()));
    check!(prismpdf_object_boolean(null(), null_mut()));
    check!(prismpdf_object_integer(null(), null_mut()));
    check!(prismpdf_object_real(null(), null_mut()));
    check!(prismpdf_object_bytes(null(), null_mut(), null_mut()));
    check!(prismpdf_object_array_len(null(), null_mut()));
    check!(prismpdf_object_array_get(null(), 0, null_mut()));
    check!(prismpdf_object_dictionary_len(null(), null_mut()));
    check!(prismpdf_object_dictionary_get(null(), null(), 0, null_mut()));
    check!(prismpdf_object_stream_raw(null(), null_mut(), null_mut()));
    check!(prismpdf_object_reference(null(), null_mut(), null_mut()));
    check!(prismpdf_object_array_push(null_mut(), null()));
    check!(prismpdf_object_dictionary_set(null_mut(), null(), 0, null()));
    check!(prismpdf_edit_set_object(null_mut(), 0, 0, null()));
    check!(prismpdf_edit_commit(null_mut(), null(), PrismPdfEditCommitMode::Incremental, null_mut()));
    check!(prismpdf_document_open_report(null(), null_mut()));
    check!(prismpdf_open_report_mode(null(), null_mut()));
    check!(prismpdf_open_report_diagnostic_count(null(), null_mut()));
    check!(prismpdf_open_report_diagnostic(null(), 0, null_mut(), null_mut(), null_mut()));
    check!(prismpdf_transform_report_bytes(null(), null_mut(), null_mut()));
    check!(prismpdf_transform_report_rewrite_mode(null(), null_mut()));
    check!(prismpdf_transform_report_signature_effect(null(), null_mut()));
    check!(prismpdf_transform_report_structure_effect(null(), null_mut()));
    check!(prismpdf_document_page_count(null(), null_mut()));
    check!(prismpdf_document_version(null(), null_mut(), null_mut()));
    check!(prismpdf_page_text(null(), 0, null_mut()));
    check!(prismpdf_document_save(null(), null_mut(), null_mut()));
    check!(prismpdf_document_save_report(null(), null_mut()));
    check!(prismpdf_document_save_compact(null(), null_mut(), null_mut()));
    check!(prismpdf_document_save_compact_report(null(), null_mut()));
    check!(prismpdf_document_save_encrypted(null(), null(), 0, null(), 0, 0, null_mut(), null_mut()));
    check!(prismpdf_document_extract_pages(null(), null(), 0, null_mut(), null_mut()));
    check!(prismpdf_document_extract_pages_report(null(), null(), 0, null_mut()));
    check!(prismpdf_document_rotate_page(null(), 0, 0, null_mut(), null_mut()));
    check!(prismpdf_document_rotate_page_report(null(), 0, 0, null_mut()));
    check!(prismpdf_merge_report(null(), 0, null_mut()));
    check!(prismpdf_merge(null(), 0, null_mut(), null_mut()));
    check!(prismpdf_document_text(null(), null_mut()));
    check!(prismpdf_measure_text(null(), null(), null_mut()));
    check!(prismpdf_wrap_text(null(), null(), 0.0, null_mut()));
    check!(prismpdf_image_source_size(null(), null_mut(), null_mut()));
    check!(prismpdf_table_set_font(null_mut(), null(), null()));
    check!(prismpdf_table_add_row(null_mut(), null(), 0));
    check!(prismpdf_table_set_size(null_mut(), 0.0));
    check!(prismpdf_table_set_leading(null_mut(), 0.0));
    check!(prismpdf_table_set_padding(null_mut(), 0.0));
    check!(prismpdf_table_set_border(null_mut(), 0.0));
    check!(prismpdf_table_set_header_row(null_mut(), false));
    check!(prismpdf_table_set_align(null_mut(), PrismPdfAlign::Left));
    check!(prismpdf_flow_build(null_mut(), null_mut(), null_mut()));
    check!(prismpdf_flow_into_builder(null_mut(), null_mut()));
    check!(prismpdf_flow_set_tagged(null_mut(), null()));
    check!(prismpdf_flow_embed_font(null_mut(), null(), null(), 0));
    check!(prismpdf_flow_set_info(null_mut(), null(), null()));
    check!(prismpdf_flow_add_bookmark(null_mut(), null()));
    check!(prismpdf_flow_text(null_mut(), null(), null()));
    check!(prismpdf_flow_heading(null_mut(), 0, null(), null()));
    check!(prismpdf_flow_list(null_mut(), null(), null(), 0, PrismPdfListStyle::Bullet));
    check!(prismpdf_flow_table(null_mut(), null()));
    check!(prismpdf_flow_image(null_mut(), null(), 0.0, 0.0));
    check!(prismpdf_flow_image_fit(null_mut(), null(), 0.0));
    check!(prismpdf_flow_figure(null_mut(), null(), 0.0, 0.0, null()));
    check!(prismpdf_flow_figure_fit(null_mut(), null(), 0.0, null()));
    check!(prismpdf_flow_figure_with_caption(null_mut(), null(), 0.0, 0.0, null(), null(), null()));
    check!(prismpdf_flow_note(null_mut(), null(), null(), null()));
    check!(prismpdf_flow_fenote(null_mut(), null(), null(), null(), null(), 0));
    check!(prismpdf_flow_title_element(null_mut(), null(), null()));
    check!(prismpdf_flow_formula(null_mut(), null(), null(), null()));
    check!(prismpdf_flow_set_header(null_mut(), null(), null()));
    check!(prismpdf_flow_set_footer(null_mut(), null(), null()));
    check!(prismpdf_flow_space(null_mut(), 0.0));
    check!(prismpdf_flow_page_break(null_mut()));
    check!(prismpdf_flow_page_count(null(), null_mut()));
    check!(prismpdf_flow_cursor_y(null(), null_mut()));
    check!(prismpdf_flow_set_title(null_mut(), null()));
    check!(prismpdf_flow_set_author(null_mut(), null()));
    check!(prismpdf_document_save_encrypted_with(null(), null(), 0, null(), 0, 0, false, 0, null_mut(), null_mut()));
    check!(prismpdf_document_save_encrypted_public_key(null(), null(), null(), 0, 0, false, 0, null_mut(), null_mut()));
    check!(prismpdf_document_save_encrypted_with_mac(null(), null(), 0, null(), 0, 0, false, 0, null_mut(), null_mut()));
    check!(prismpdf_document_verify_pdf_mac(null(), null(), 0, null_mut()));
    check!(prismpdf_sign_settings_set_name(null_mut(), null()));
    check!(prismpdf_sign_settings_set_reason(null_mut(), null()));
    check!(prismpdf_sign_settings_set_location(null_mut(), null()));
    check!(prismpdf_sign_settings_set_contact_info(null_mut(), null()));
    check!(prismpdf_sign_settings_set_signing_time(null_mut(), 0));
    check!(prismpdf_sign_settings_set_pades(null_mut(), false));
    check!(prismpdf_sign_settings_set_appearance(null_mut(), 0, null(), null()));
    check!(prismpdf_sign_settings_set_timestamp(null_mut(), null(), 0, null(), 0, 0, 0));
    check!(prismpdf_document_sign(null(), null(), 0, null(), 0, null_mut(), null_mut()));
    check!(prismpdf_document_sign_with(null(), null(), 0, null(), 0, null(), null_mut(), null_mut()));
    check!(prismpdf_document_sign_with_mac(null(), null(), 0, null(), 0, null(), null(), 0, null_mut(), null_mut()));
    check!(prismpdf_document_timestamp(null(), null(), 0, null(), 0, 0, false, null_mut(), null_mut()));
    check!(prismpdf_document_verify_signatures(null(), null_mut()));
    check!(prismpdf_document_verify_signatures_with(null(), null(), null(), 0, null_mut()));
    check!(prismpdf_document_verify_signatures_ltv(null(), null(), null(), 0, null_mut()));
    check!(prismpdf_signature_list_len(null(), null_mut()));
    check!(prismpdf_signature_list_get(null(), 0, null_mut()));
    check!(prismpdf_signature_valid(null(), null_mut()));
    check!(prismpdf_signature_signer(null(), null_mut()));
    check!(prismpdf_signature_covered_bytes(null(), null_mut()));
    check!(prismpdf_signature_signing_time(null(), null_mut()));
    check!(prismpdf_signature_timestamp_time(null(), null_mut()));
    check!(prismpdf_signature_trusted(null(), null_mut()));
    check!(prismpdf_signature_pades(null(), null_mut()));
    check!(prismpdf_signature_revocation(null(), null_mut()));
    check!(prismpdf_pdfa_code(PrismPdfPdfAConformance::A1b, null_mut()));
    check!(prismpdf_xmp_metadata_add_author(null_mut(), null()));
    check!(prismpdf_builder_make_pdfa(null_mut(), PrismPdfPdfAConformance::A1b, null(), null_mut()));
    check!(prismpdf_builder_make_pdfa_with_output_intent(null_mut(), PrismPdfPdfAConformance::A1b, null(), null(), 0, 0, null(), null_mut()));
    check!(prismpdf_builder_make_pdfua(null_mut(), null(), null(), null_mut()));
    check!(prismpdf_builder_make_pdfua2(null_mut(), null(), null(), null_mut()));
    check!(prismpdf_builder_set_output_intent(null_mut(), null(), 0, 0, null()));
    check!(prismpdf_xmp_metadata_set_title(null_mut(), null()));
    check!(prismpdf_xmp_metadata_set_subject(null_mut(), null()));
    check!(prismpdf_xmp_metadata_set_keywords(null_mut(), null()));
    check!(prismpdf_xmp_metadata_set_creator_tool(null_mut(), null()));
    check!(prismpdf_xmp_metadata_set_producer(null_mut(), null()));
    check!(prismpdf_xmp_metadata_set_create_date(null_mut(), null()));
    check!(prismpdf_xmp_metadata_set_modify_date(null_mut(), null()));
    check!(prismpdf_open_options_set_max_depth(null_mut(), 0));
    check!(prismpdf_open_options_set_max_objstm_objects(null_mut(), 0));
    check!(prismpdf_open_options_set_max_objects(null_mut(), 0));
    check!(prismpdf_open_options_set_password(null_mut(), null(), 0));
    check!(prismpdf_document_open_with_options(null(), 0, null(), null_mut()));
    check!(prismpdf_document_open_with_limits(null(), 0, null(), null_mut()));
    check!(prismpdf_document_open_with_private_key(null(), 0, null(), 0, null(), 0, null_mut()));
    check!(prismpdf_document_min_version(null(), null_mut(), null_mut()));
    check!(prismpdf_document_save_as(null(), 0, 0, null_mut(), null_mut()));
    check!(prismpdf_document_save_as_report(null(), 0, 0, null_mut()));
    check!(prismpdf_document_save_packed(null(), null_mut(), null_mut()));
    check!(prismpdf_document_save_packed_report(null(), null_mut()));
    check!(prismpdf_string_list_len(null(), null_mut()));
    check!(prismpdf_string_list_get(null(), 0, null_mut()));
    check!(prismpdf_document_structure_namespaces(null(), null_mut()));
    check!(prismpdf_document_signature_vri_keys(null(), null_mut()));
    assert!(failures.is_empty(), "expected NullArgument from:\n{}", failures.join("\n"));
}
